@startuml
set namespaceSeparator ::

class "macbear_3d::src::mesh::animator.dart::M3Animator" {
  +List<GltfAnimation> animations
  +Map<int, GltfNode> nodes
  +List<GltfNode>? allNodes
  -int _currentAnimationIndex
  -double _currentTime
  +bool isPlaying
  +bool loop
  +double playRate
  -int? _prevAnimationIndex
  -double _prevTime
  -double _fadeTime
  -double _fadeDuration
  +bool isFading
  +void play()
  +void crossFade()
  +void update()
  -double _advanceTime()
  -void _updateAnimation()
  -void _updateHierarchy()
  -void _applySampler()
  -Quaternion _slerp()
  -Vector3 _getVector3()
  -Quaternion _getQuaternion()
}

class "macbear_3d::src::mesh::mesh.dart::M3Skin" {
  +List<Matrix4> boneMatrices
  +List<Matrix4>? inverseBindMatrices
  +List<GltfNode>? jointNodes
  -int _debugCount
  +int boneCount
  +void update()
  +M3Skin clone()
}

class "macbear_3d::src::mesh::mesh.dart::M3Mesh" {
  +M3Material mtr
  +M3Geom geom
  +Matrix4 initMatrix
  +M3Skin? skin
  +M3Animator? animator
  +List<GltfNode>? nodes
  {static} +dynamic load()
  {static} -M3Mesh _meshFromGltfDoc()
  +M3Mesh clone()
}

"macbear_3d::src::mesh::mesh.dart::M3Mesh" o-- "macbear_3d::src::texture::material.dart::M3Material"
"macbear_3d::src::mesh::mesh.dart::M3Mesh" o-- "macbear_3d::src::geom::geom.dart::M3Geom"
"macbear_3d::src::mesh::mesh.dart::M3Mesh" o-- "vector_math::vector_math.dart::Matrix4"
"macbear_3d::src::mesh::mesh.dart::M3Mesh" o-- "macbear_3d::src::mesh::mesh.dart::M3Skin"
"macbear_3d::src::mesh::mesh.dart::M3Mesh" o-- "macbear_3d::src::mesh::animator.dart::M3Animator"

class "macbear_3d::src::mesh::obj_loader.dart::M3ObjLoader" {
  {static} +dynamic load()
  {static} +M3Geom parse()
  {static} -void _processVertex()
}

class "macbear_3d::src::anim::bvh_data.dart::BvhJoint" {
  +String name
  +Vector3 offset
  +List<String> channels
  +List<BvhJoint> children
  +int? channelOffset
  +bool isEndSite
  +String toString()
}

"macbear_3d::src::anim::bvh_data.dart::BvhJoint" o-- "vector_math::vector_math.dart::Vector3"

class "macbear_3d::src::anim::bvh_data.dart::BvhData" {
  +BvhJoint root
  +int frameCount
  +double frameTime
  +List<BvhJoint> allJoints
  +List<List<double>> frames
  +double duration
  +String toString()
}

"macbear_3d::src::anim::bvh_data.dart::BvhData" o-- "macbear_3d::src::anim::bvh_data.dart::BvhJoint"

class "macbear_3d::src::anim::bvh_parser.dart::BvhParser" {
  {static} +BvhData parse()
}

class "macbear_3d::src::anim::bvh_skeleton.dart::BvhSkeleton" {
  +BvhData data
  +BvhAnimator animator
  +Map<BvhJoint, M3Transform> jointTransforms
  +List<M3Entity> jointEntities
  +List<M3Entity> boneEntities
  +M3Transform rootTransform
  {static} +dynamic load()
  +void addToScene()
  -void _createHierarchy()
  +void update()
  -void _syncEntities()
}

"macbear_3d::src::anim::bvh_skeleton.dart::BvhSkeleton" o-- "macbear_3d::src::anim::bvh_data.dart::BvhData"
"macbear_3d::src::anim::bvh_skeleton.dart::BvhSkeleton" o-- "macbear_3d::src::anim::bvh_animator.dart::BvhAnimator"
"macbear_3d::src::anim::bvh_skeleton.dart::BvhSkeleton" o-- "macbear_3d::src::scene::transform.dart::M3Transform"

class "macbear_3d::src::anim::bvh_animator.dart::BvhAnimator" {
  +BvhData data
  -double _time
  +bool isPlaying
  +bool loop
  +double speed
  +void update()
  -void _applyJointAnimation()
}

"macbear_3d::src::anim::bvh_animator.dart::BvhAnimator" o-- "macbear_3d::src::anim::bvh_data.dart::BvhData"

class "macbear_3d::src::util::platform::platform_info.dart::GraphicsInfo" {
  +String vendor
  +String renderer
  +String version
  +String shadingVersion
  +String toString()
}

class "macbear_3d::src::util::platform::platform_info.dart::PlatformInfo" {
  {static} -Map<int, String> _glParamNames
  {static} +String getOS()
  {static} +GraphicsInfo getGraphicsInfo()
  {static} +void checkGLExtensions()
}

class "macbear_3d::src::util::constants.dart::M3Constants" {
  {static} +Matrix3 rotXNeg90
  {static} +Matrix3 rotXPos90
  {static} +Matrix4 biasMatrix
  {static} +M3Material mtrDefault
  {static} +M3Material mtrMetal
  {static} +M3Material mtrWood
  {static} +M3Material mtrPlastic
  {static} +M3Material mtrGlass
}

"macbear_3d::src::util::constants.dart::M3Constants" o-- "vector_math::vector_math.dart::Matrix3"
"macbear_3d::src::util::constants.dart::M3Constants" o-- "vector_math::vector_math.dart::Matrix4"
"macbear_3d::src::util::constants.dart::M3Constants" o-- "macbear_3d::src::texture::material.dart::M3Material"

class "macbear_3d::src::util::constants.dart::M3Package" {
  {static} +String? name
  {static} +TextStyle textStyleRobotoMono()
  {static} +String asset()
}

class "macbear_3d::src::util::constants.dart::M3Axis" {
  +int index
  {static} +List<M3Axis> values
  {static} +M3Axis x
  {static} +M3Axis y
  {static} +M3Axis z
}

"macbear_3d::src::util::constants.dart::M3Axis" o-- "macbear_3d::src::util::constants.dart::M3Axis"
"dart::core::Enum" <|-- "macbear_3d::src::util::constants.dart::M3Axis"

class "macbear_3d::src::util::euler.dart::M3Euler" {
  +double yaw
  +double pitch
  +double roll
  +void setEuler()
  +void setToward()
  +void normalizeAngle()
  +Matrix3 getMatrix3()
  +String toString()
}

class "macbear_3d::src::util::utility.dart::M3Utility" {
  {static} +dynamic isAssetExists()
}

class "macbear_3d::src::util::noise.dart::M3Noise" {
  {static} -List<int> _p
  {static} -List<int> _permutation
  {static} -bool _init
  {static} -void _ensureInit()
  {static} +double fade()
  {static} +double lerp()
  {static} +double grad()
  {static} +double perlin2D()
  {static} +double fBm()
}

class "macbear_3d::src::input::keyboard.dart::M3KeyboardManager" {
  -Set<PhysicalKeyboardKey> _pressed
  +Duration repeatDelay
  +Duration repeatInterval
  -Map<PhysicalKeyboardKey, Timer> _repeatTimers
  +Map<LogicalKeyboardKey, String> keyMap
  -bool _started
  +void Function(KeyDownEvent)? onKeyDown
  +void Function(KeyUpEvent)? onKeyUp
  +void Function(PhysicalKeyboardKey)? onKeyRepeat
  +void Function(String)? onActionDown
  +void Function(String)? onActionUp
  +void start()
  +void stop()
  +bool isPressed()
  +String? getActionByKey()
  -bool _handleKeyEvent()
  -void _startRepeat()
  -void _stopRepeat()
  -void _clearTimers()
  -void _initDefaultMap()
}

"macbear_3d::src::input::keyboard.dart::M3KeyboardManager" o-- "null::void Function(KeyDownEvent)"
"macbear_3d::src::input::keyboard.dart::M3KeyboardManager" o-- "null::void Function(KeyUpEvent)"
"macbear_3d::src::input::keyboard.dart::M3KeyboardManager" o-- "null::void Function(PhysicalKeyboardKey)"
"macbear_3d::src::input::keyboard.dart::M3KeyboardManager" o-- "null::void Function(String)"

class "macbear_3d::src::input::touch.dart::M3TouchPoint" {
  +Vector2 position
  +int buttons
  +double time
  +String toString()
}

"macbear_3d::src::input::touch.dart::M3TouchPoint" o-- "vector_math::vector_math.dart::Vector2"

class "macbear_3d::src::input::touch.dart::M3PinchInfo" {
  +double scale
  +Vector2 center
  +double distance
  +String toString()
}

"macbear_3d::src::input::touch.dart::M3PinchInfo" o-- "vector_math::vector_math.dart::Vector2"

class "macbear_3d::src::input::touch.dart::M3Touch" {
  +int id
  +List<M3TouchPoint> path
  +bool isActive
  +int smoothWindow
  +double x
  +double y
  +Vector2 offset
  +int buttons
  +void touchDown()
  +void touchMove()
  +void touchUp()
  +void clear()
  +Vector2? smoothedVelocity()
  +double? smoothedDirection()
}

"macbear_3d::src::input::touch.dart::M3Touch" o-- "vector_math::vector_math.dart::Vector2"

class "macbear_3d::src::input::touch.dart::M3TouchManager" {
  +Map<int, M3Touch> touches
  -double? _prevPinchDistance
  +M3Touch onTouchDown()
  +M3Touch? onTouchMove()
  +M3Touch? onTouchUp()
  +M3PinchInfo? getPinch()
  +Vector2 getFingerDelta()
  +void clearAll()
  +void clearInactive()
}

abstract class "macbear_3d::src::input::touch.dart::M3InputController" {
  +void onTouchDown()
  +void onTouchMove()
  +void onTouchUp()
  +void onScroll()
  +void onKeyDown()
  +void onKeyUp()
  +void onKeyRepeat()
  +void update()
}

class "macbear_3d::src::input::touch.dart::M3CameraOrbitController" {
  +M3Camera camera
  +void onTouchDown()
  +void onTouchUp()
  +void onTouchMove()
  +void onScroll()
  +void applyZoom()
  +void applyOrbit()
  +void applyPan()
  +void onKeyDown()
  +void onKeyUp()
  +void onKeyRepeat()
  +void update()
}

"macbear_3d::src::input::touch.dart::M3CameraOrbitController" o-- "macbear_3d::src::scene::camera.dart::M3Camera"
"macbear_3d::src::input::touch.dart::M3InputController" <|-- "macbear_3d::src::input::touch.dart::M3CameraOrbitController"

class "macbear_3d::src::gltf::gltf_loader.dart::M3GltfLoader" {
  {static} +dynamic load()
  {static} +dynamic loadFromBytes()
  {static} -bool _isGlb()
  {static} -dynamic _parseGlb()
  {static} -dynamic _parseGltf()
}

class "macbear_3d::src::gltf::gltf_accessor.dart::GltfAccessor" {
  {static} +int BYTE
  {static} +int UNSIGNED_BYTE
  {static} +int SHORT
  {static} +int UNSIGNED_SHORT
  {static} +int UNSIGNED_INT
  {static} +int FLOAT
  {static} +Float32List getFloatList()
  {static} +Uint16List getUint16List()
  {static} +Uint32List getUint32List()
  {static} -int _getComponentCount()
}

class "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument" {
  +String name
  +Map<String, dynamic> json
  +Uint8List? embeddedBin
  +List<GltfMesh> meshes
  +List<GltfMaterial> materials
  +List<GltfTexture> textures
  +List<GltfImage> images
  +List<GltfSkin> skins
  +List<GltfNode> nodes
  +List<GltfAnimation> animations
  +List<int> rootNodes
  +List<dynamic> runtimeTextures
  {static} +GltfDocument parse()
  -void _parseAll()
  +Float32List getFloatAccessor()
  +Uint16List getUint16Accessor()
  +Uint32List getUint32Accessor()
  +int getAccessorCount()
  +int getAccessorComponentType()
  +Uint8List getBufferViewData()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfDocument" o-- "dart::typed_data::Uint8List"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfImage" {
  +String? uri
  +int? bufferView
  +String? mimeType
  +String? name
  {static} +GltfImage parse()
}

class "macbear_3d::src::gltf::gltf_parser.dart::GltfTexture" {
  +int? sampler
  +int? source
  +String? name
  {static} +GltfTexture parse()
}

class "macbear_3d::src::gltf::gltf_parser.dart::GltfMaterial" {
  +String name
  +Vector4 baseColorFactor
  +int? baseColorTextureIndex
  +double metallicFactor
  +double roughnessFactor
  {static} +GltfMaterial parse()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfMaterial" o-- "vector_math::vector_math.dart::Vector4"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfSkin" {
  +GltfDocument document
  +String name
  +int? inverseBindMatricesAccessor
  +List<int> joints
  {static} +GltfSkin parse()
  +Float32List? getInverseBindMatrices()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfSkin" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfMesh" {
  +GltfDocument document
  +int index
  +String name
  +List<GltfPrimitive> primitives
  {static} +GltfMesh parse()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfMesh" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfPrimitive" {
  +GltfDocument document
  +int? positionAccessor
  +int? normalAccessor
  +int? texCoordAccessor
  +int? jointAccessor
  +int? weightAccessor
  +int? indicesAccessor
  +int mode
  +int? materialIndex
  +int? skinIndex
  +int vertexCount
  {static} +GltfPrimitive parse()
  +Float32List? getPositions()
  +Float32List? getNormals()
  +Float32List? getTexCoords()
  +Uint16List? getJoints()
  +Float32List? getWeights()
  +List<int>? getIndices()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfPrimitive" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfNode" {
  +GltfDocument document
  +String name
  +int? meshIndex
  +int? skinIndex
  +List<int> children
  +Vector3 translation
  +Quaternion rotation
  +Vector3 scale
  +Matrix4? matrix
  +Matrix4 worldMatrix
  {static} +GltfNode parse()
  +void computeWorldMatrix()
  +GltfNode clone()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfNode" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"
"macbear_3d::src::gltf::gltf_parser.dart::GltfNode" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::gltf::gltf_parser.dart::GltfNode" o-- "vector_math::vector_math.dart::Quaternion"
"macbear_3d::src::gltf::gltf_parser.dart::GltfNode" o-- "vector_math::vector_math.dart::Matrix4"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfAnimation" {
  +GltfDocument document
  +String name
  +List<GltfAnimationChannel> channels
  +List<GltfAnimationSampler> samplers
  {static} +GltfAnimation parse()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfAnimation" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfAnimationChannel" {
  +GltfDocument document
  +int samplerIndex
  +int? targetNodeIndex
  +String targetPath
  {static} +GltfAnimationChannel parse()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfAnimationChannel" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"

class "macbear_3d::src::gltf::gltf_parser.dart::GltfAnimationSampler" {
  +GltfDocument document
  +int inputAccessor
  +int outputAccessor
  +String interpolation
  {static} +GltfAnimationSampler parse()
  +Float32List getInputs()
  +Float32List getOutputs()
}

"macbear_3d::src::gltf::gltf_parser.dart::GltfAnimationSampler" o-- "macbear_3d::src::gltf::gltf_parser.dart::GltfDocument"

class "macbear_3d::src::geom::geom.dart::_M3Indices" {
  -int _primitiveType
  -int _count
  -Buffer _indexBuffer
  +RenderingContext gl
  +int primitiveCount
  +void draw()
  +void dispose()
}

"macbear_3d::src::geom::geom.dart::_M3Indices" o-- "flutter_angle::shared::classes.dart::Buffer"
"macbear_3d::src::geom::geom.dart::_M3Indices" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::geom::geom.dart::M3Bounding" {
  +Aabb3 aabb
  +Sphere sphere
}

"macbear_3d::src::geom::geom.dart::M3Bounding" o-- "vector_math::vector_math.dart::Aabb3"
"macbear_3d::src::geom::geom.dart::M3Bounding" o-- "vector_math::vector_math.dart::Sphere"

abstract class "macbear_3d::src::geom::geom.dart::M3Geom" {
  {static} +int radialSegments
  +String name
  +M3Bounding localBounding
  -int _vertexCount
  -Vector3List? _vertices
  -Vector3List? _normals
  -Vector2List? _uvs
  -Vector3List? _colors
  -Uint16List? _joints
  -Float32List? _weights
  -Buffer? _vertexBuffer
  -Buffer? _normalBuffer
  -Buffer? _uvBuffer
  -Buffer? _colorBuffer
  -Buffer? _jointBuffer
  -Buffer? _weightBuffer
  -List<_M3Indices> _faceIndices
  -List<_M3Indices> _edgeIndices
  +RenderingContext gl
  +int vertexCount
  +int getTriangleCount()
  +String toString()
  -void _init()
  -void _createVBO()
  +void computeNormals()
  -void _generateEdgeIndices()
  +void dispose()
  +void draw()
}

"macbear_3d::src::geom::geom.dart::M3Geom" o-- "macbear_3d::src::geom::geom.dart::M3Bounding"
"macbear_3d::src::geom::geom.dart::M3Geom" o-- "vector_math::vector_math_lists.dart::Vector3List"
"macbear_3d::src::geom::geom.dart::M3Geom" o-- "vector_math::vector_math_lists.dart::Vector2List"
"macbear_3d::src::geom::geom.dart::M3Geom" o-- "dart::typed_data::Uint16List"
"macbear_3d::src::geom::geom.dart::M3Geom" o-- "dart::typed_data::Float32List"
"macbear_3d::src::geom::geom.dart::M3Geom" o-- "flutter_angle::shared::classes.dart::Buffer"
"macbear_3d::src::geom::geom.dart::M3Geom" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::geom::geom.dart::M3DebugAxisGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3DebugAxisGeom"

class "macbear_3d::src::geom::geom.dart::M3DebugSphereGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3DebugSphereGeom"

class "macbear_3d::src::geom::geom.dart::M3BoxGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3BoxGeom"

class "macbear_3d::src::geom::geom.dart::M3CapsuleGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3CapsuleGeom"

class "macbear_3d::src::geom::geom.dart::M3CylinderGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3CylinderGeom"

class "macbear_3d::src::geom::geom.dart::M3EllipsoidGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3EllipsoidGeom"

class "macbear_3d::src::geom::geom.dart::M3OctahedralGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3OctahedralGeom"

class "macbear_3d::src::geom::geom.dart::M3PlaneGeom" {
  {static} +double formulaZ()
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3PlaneGeom"

class "macbear_3d::src::geom::geom.dart::M3PyramidGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3PyramidGeom"

class "macbear_3d::src::geom::geom.dart::M3SphereGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3SphereGeom"

class "macbear_3d::src::geom::geom.dart::M3TerrainGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3TerrainGeom"

class "macbear_3d::src::geom::geom.dart::M3TorusGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3TorusGeom"

class "macbear_3d::src::geom::geom.dart::M3TextGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3TextGeom"

class "macbear_3d::src::geom::geom.dart::M3Contour" {
  +List<M3ContourInfo> infos
  +List<List<Vector2>> normalizedOuters
  +List<List<Vector2>> normalizedHoles
  +List<int> outerOrigIndices
  +List<int> holeOrigIndices
  {static} -double _getSignedArea()
  {static} -bool _isPointInPolygon()
  {static} -bool _isContourInside()
}

class "macbear_3d::src::geom::geom.dart::M3ContourInfo" {
  +List<Vector2> points
  +double area
  +int index
  +M3ContourInfo? parent
}

"macbear_3d::src::geom::geom.dart::M3ContourInfo" o-- "macbear_3d::src::geom::geom.dart::M3ContourInfo"

class "macbear_3d::src::geom::geom.dart::M3GltfGeom" {
  {static} -int _glMode()
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3GltfGeom"

class "macbear_3d::src::geom::geom.dart::M3ObjGeom" {
}

"macbear_3d::src::geom::geom.dart::M3Geom" <|-- "macbear_3d::src::geom::geom.dart::M3ObjGeom"

class "macbear_3d::src::geom::text::ttf_parser.dart::M3TrueTypeParser" {
  -ByteData _data
  -Map<String, int> _tableOFFSETS
  -int _numGlyphs
  -int _unitsPerEm
  -int _indexToLocFormat
  -List<int> _locaTable
  -Map<int, int> _cmap
  -List<double> _hMetrics
  -bool _isOTF
  -List<Uint8List> _charStrings
  -List<Uint8List> _globalSubrs
  -List<Uint8List> _localSubrs
  -_CmapFormat4Data? _cmapFormat4Data
  -List<_CmapGroup>? _cmapFormat12Data
  -Map<int, List<Uint8List>> _fdLocalSubrs
  -List<Uint8List> _fdArray
  -Map<int, int> _fdSelect
  -Map<int, int> _regionIndexCounts
  +bool isOTF
  +bool isTTF
  {static} +dynamic loadFromAsset()
  -void _parseFile()
  -void _parseFileInternal()
  -String _readTag()
  -void _parseHead()
  -void _parseMaxp()
  -void _parseLoca()
  -void _parseCmap()
  -void _parseCmapFormat4()
  -void _parseCmapFormat12()
  +int getGlyphIndex()
  -void _parseHmtx()
  -void _parseCFF2()
  -void _parseVarStore()
  -void _parseFDSelect()
  -List<Uint8List> _getLocalSubrsForGlyph()
  -List<Uint8List> _readINDEX()
  -Map<int, List<double>> _readDICT()
  -int _readReal()
  +double getAdvanceWidth()
  +List<List<Vector2>> getGlyphContours()
  -List<List<Vector2>> _getGlyphContoursCFF()
  -void _addCubic()
}

"macbear_3d::src::geom::text::ttf_parser.dart::M3TrueTypeParser" o-- "dart::typed_data::ByteData"
"macbear_3d::src::geom::text::ttf_parser.dart::M3TrueTypeParser" o-- "macbear_3d::src::geom::text::ttf_parser.dart::_CmapFormat4Data"

class "macbear_3d::src::geom::text::ttf_parser.dart::_CmapFormat4Data" {
  +int segCount
  +List<int> endCodes
  +List<int> startCodes
  +List<int> idDeltas
  +List<int> idRangeOffsets
  +int idRangeOffsetOffset
}

class "macbear_3d::src::geom::text::ttf_parser.dart::_CmapGroup" {
  +int start
  +int end
  +int startGID
}

class "macbear_3d::src::geom::text::ear_clipping.dart::M3EarClipping" {
  +dynamic static()
  +dynamic triangulate()
  {static} -bool _isEar()
  {static} -bool _isPointInTriangle()
  {static} -void _eliminateHoles()
}

class "macbear_3d::src::program::program.dart::M3Program" {
  -WebGLShader _shaderVert
  -WebGLShader _shaderFrag
  +Program program
  +UniformLocation uniformProjection
  +UniformLocation uniformModel
  +UniformLocation uniformMVP
  +UniformLocation uniformTexMatrix
  +UniformLocation uniformSamplerDiffuse
  +UniformLocation uniformCameraViewport
  +UniformLocation attribVertex
  +UniformLocation attribColor
  +UniformLocation attribNormal
  +UniformLocation attribUV
  +UniformLocation uniformColor
  +UniformLocation uniformBoneCount
  +UniformLocation uniformBoneMatrixArray
  +UniformLocation uniformBoneMatrixArrayIT
  +UniformLocation attribBoneIndex
  +UniformLocation attribBoneWeight
  +RenderingContext gl
  {static} +bool isLocationValid()
  -String _ensureVersionAtStart()
  +void initLocation()
  +void dispose()
  +void setProjectionMatrix()
  +void setModelMatrix()
  +void setMVPMatrix()
  +void applyCamera()
  +void setMatrices()
  +void setMaterial()
  +void setSkinning()
  +void disableAttribute()
}

"macbear_3d::src::program::program.dart::M3Program" o-- "flutter_angle::shared::classes.dart::WebGLShader"
"macbear_3d::src::program::program.dart::M3Program" o-- "flutter_angle::shared::classes.dart::Program"
"macbear_3d::src::program::program.dart::M3Program" o-- "flutter_angle::shared::classes.dart::UniformLocation"
"macbear_3d::src::program::program.dart::M3Program" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::program::program.dart::M3ProgramEye" {
  +UniformLocation uniformEyePosition
  +void initLocation()
  +void setEye()
  +void setMatrices()
}

"macbear_3d::src::program::program.dart::M3ProgramEye" o-- "flutter_angle::shared::classes.dart::UniformLocation"
"macbear_3d::src::program::program.dart::M3Program" <|-- "macbear_3d::src::program::program.dart::M3ProgramEye"

class "macbear_3d::src::program::program.dart::M3ProgramLighting" {
  +void initLocation()
  +void setMatrices()
  +void setMaterial()
}

"macbear_3d::src::program::program.dart::M3ProgramEye" <|-- "macbear_3d::src::program::program.dart::M3ProgramLighting"
"macbear_3d::src::program::program.dart::M3LightingShader" <|-- "macbear_3d::src::program::program.dart::M3ProgramLighting"

abstract class "macbear_3d::src::program::program.dart::M3LightingShader" {
  +UniformLocation uniformAmbient
  +UniformLocation uniformDiffuse
  +UniformLocation uniformSpecular
  +UniformLocation uniformLightPosition
  +UniformLocation uniformParamPBR
  +UniformLocation uniformSamplerEnvironment
  -M3Light? _light
  +RenderingContext gl
  +void initLightingLocation()
  +void applyLight()
}

"macbear_3d::src::program::program.dart::M3LightingShader" o-- "flutter_angle::shared::classes.dart::UniformLocation"
"macbear_3d::src::program::program.dart::M3LightingShader" o-- "macbear_3d::src::scene::light.dart::M3Light"
"macbear_3d::src::program::program.dart::M3LightingShader" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

abstract class "macbear_3d::src::program::program.dart::M3ProgramShadow" {
  +UniformLocation uniformSamplerShadowmap
  +UniformLocation uniformShadowmapSize
  +UniformLocation uniformNormalBias
  +void initLocation()
  +void applyLight()
  +void bindShadow()
}

"macbear_3d::src::program::program.dart::M3ProgramShadow" o-- "flutter_angle::shared::classes.dart::UniformLocation"
"macbear_3d::src::program::program.dart::M3ProgramLighting" <|-- "macbear_3d::src::program::program.dart::M3ProgramShadow"

class "macbear_3d::src::program::program.dart::M3ProgramShadowmap" {
  +UniformLocation uniformMatrixShadowmap
  +void initLocation()
  +void setMatrices()
}

"macbear_3d::src::program::program.dart::M3ProgramShadowmap" o-- "flutter_angle::shared::classes.dart::UniformLocation"
"macbear_3d::src::program::program.dart::M3ProgramShadow" <|-- "macbear_3d::src::program::program.dart::M3ProgramShadowmap"

class "macbear_3d::src::program::program.dart::M3ProgramShadowCSM" {
  +UniformLocation uniformMatrixCSM
  +UniformLocation uniformDepthCSM
  +void initLocation()
  +void applyCamera()
  +void setMatrices()
}

"macbear_3d::src::program::program.dart::M3ProgramShadowCSM" o-- "flutter_angle::shared::classes.dart::UniformLocation"
"macbear_3d::src::program::program.dart::M3ProgramShadow" <|-- "macbear_3d::src::program::program.dart::M3ProgramShadowCSM"

class "macbear_3d::src::texture::material.dart::M3Material" {
  +Vector4 diffuse
  +Vector3 specular
  +double shininess
  +double reflection
  +double metallic
  +double roughness
  +M3Texture texDiffuse
  +Matrix3 texMatrix
  +M3Material clone()
  +void copyFrom()
}

"macbear_3d::src::texture::material.dart::M3Material" o-- "vector_math::vector_math.dart::Vector4"
"macbear_3d::src::texture::material.dart::M3Material" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::texture::material.dart::M3Material" o-- "macbear_3d::src::texture::texture.dart::M3Texture"
"macbear_3d::src::texture::material.dart::M3Material" o-- "vector_math::vector_math.dart::Matrix3"

class "macbear_3d::src::texture::texture.dart::M3Texture" {
  {static} -List<int> _cubeMapFaceTargets
  +String name
  -WebGLTexture _texture
  +bool isCubemap
  +bool generateMipmaps
  +int texW
  +int texH
  {static} -WebGLTexture _textureNone
  +RenderingContext gl
  +WebGLTexture glTexture
  +int target
  +void setParameters()
  +void dispose()
  +void bind()
  +void unbind()
  +String toString()
  {static} +M3Texture createSolidColor()
  {static} +M3Texture createSolidColorCube()
  {static} +M3Texture createDefaultIBLCube()
  {static} +M3Texture createEmptyCubemap()
  -void _initColorPixel()
  -void _initEmptyTarget()
  -void _initCheckerboard()
  {static} +M3Texture createCheckerboard()
  {static} +M3Texture createSampleCubemap()
  {static} +dynamic loadTexture()
  {static} +dynamic loadCubemap()
  {static} +dynamic createFromBytes()
  -dynamic _loadTarget()
  -dynamic _loadTargetFromImage()
  {static} +dynamic createWoodTexture()
  {static} -dynamic _generateWoodImage()
}

"macbear_3d::src::texture::texture.dart::M3Texture" o-- "flutter_angle::shared::classes.dart::WebGLTexture"
"macbear_3d::src::texture::texture.dart::M3Texture" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::texture::texture.dart::M3TextTexture" {
  +String text
  +TextStyle style
  {static} +dynamic createFixed()
  +dynamic updateText()
  -dynamic _updateTexture()
  {static} +dynamic createFromText()
  -dynamic _makeLabelImage()
  -dynamic _createTextureFromLabel()
}

"macbear_3d::src::texture::texture.dart::M3TextTexture" o-- "flutter::src::painting::text_style.dart::TextStyle"
"macbear_3d::src::texture::texture.dart::M3Texture" <|-- "macbear_3d::src::texture::texture.dart::M3TextTexture"

class "macbear_3d::src::texture::texture.dart::M3ExternalTexture" {
  +dynamic source
  +bool isPlaying
  +GlobalKey<State<StatefulWidget>>? repaintKey
  -bool _isCapturing
  -bool _isNativeCodec
  -Uint8Array? _submitPixels
  +void dispose()
  {static} +dynamic createVideo()
  +dynamic initNativeBridge()
  +dynamic releaseNativeBridge()
  +void update()
  -dynamic _updateTextureFromNative()
  -dynamic _captureNativeFrame()
  {static} +M3ExternalTexture createFromVideo()
  +void play()
  +void pause()
  +void seekTo()
  +dynamic getDuration()
  +dynamic getPosition()
}

"macbear_3d::src::texture::texture.dart::M3ExternalTexture" o-- "flutter::src::widgets::framework.dart::GlobalKey<State<StatefulWidget>>"
"macbear_3d::src::texture::texture.dart::M3ExternalTexture" o-- "flutter_angle::native-array::index.dart::Uint8Array"
"macbear_3d::src::texture::texture.dart::M3Texture" <|-- "macbear_3d::src::texture::texture.dart::M3ExternalTexture"

abstract class "macbear_3d::src::texture::ktx_info.dart::M3GL" {
  {static} +int COMPRESSED_RGBA_ASTC_4x4_KHR
  {static} +int COMPRESSED_RGBA_ASTC_5x4_KHR
  {static} +int COMPRESSED_RGBA_ASTC_5x5_KHR
  {static} +int COMPRESSED_RGBA_ASTC_6x5_KHR
  {static} +int COMPRESSED_RGBA_ASTC_6x6_KHR
  {static} +int COMPRESSED_RGBA_ASTC_8x5_KHR
  {static} +int COMPRESSED_RGBA_ASTC_8x6_KHR
  {static} +int COMPRESSED_RGBA_ASTC_8x8_KHR
  {static} +int COMPRESSED_RGBA_ASTC_10x5_KHR
  {static} +int COMPRESSED_RGBA_ASTC_10x6_KHR
  {static} +int COMPRESSED_RGBA_ASTC_10x8_KHR
  {static} +int COMPRESSED_RGBA_ASTC_10x10_KHR
  {static} +int COMPRESSED_RGBA_ASTC_12x10_KHR
  {static} +int COMPRESSED_RGBA_ASTC_12x12_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR
  {static} +int COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR
}

class "macbear_3d::src::texture::ktx_info.dart::KtxInfo" {
  +bool isKtx2
  +int width
  +int height
  +int mipCount
  +int vkFormat
  +String formatName
  +int glFormat
  +Uint8List texData
  {static} +dynamic parseKtx()
}

"macbear_3d::src::texture::ktx_info.dart::KtxInfo" o-- "dart::typed_data::Uint8List"

class "macbear_3d::src::texture::ktx_info.dart::_Ktx2Level" {
  +int byteOffset
  +int byteLength
  +int uncompressedLength
}

class "macbear_3d::src::physics::physics_engine.dart::M3PhysicsEngine" {
  -World? _world
  -double _accumulator
  -int _maxStepsPerFrame
  +World? world
  +int maxStepsPerFrame
  +double interpolationAlpha
  +void resetWorld()
  -RigidBody _addPrimitive()
  +RigidBody addBox()
  +RigidBody addSphere()
  +RigidBody addCylinder()
  +RigidBody addCapsule()
  +void update()
  +RigidBody addGround()
  +void addBoundaryFence()
}

"macbear_3d::src::physics::physics_engine.dart::M3PhysicsEngine" o-- "oimo_physics::core::world_core.dart::World"

class "macbear_3d::src::scene::transform.dart::M3Transform" {
  -Vector3 _position
  -Quaternion _rotation
  -Vector3 _scale
  -M3Transform? _parent
  +List<M3Transform> children
  -bool _dirty
  -Matrix4 _worldMatrix
  +Vector3 position
  +Quaternion rotation
  +Vector3 scale
  +M3Transform? parent
  +bool isDirty
  +Matrix4 worldMatrix
  +void markDirty()
  -void _rebuild()
}

"macbear_3d::src::scene::transform.dart::M3Transform" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::scene::transform.dart::M3Transform" o-- "vector_math::vector_math.dart::Quaternion"
"macbear_3d::src::scene::transform.dart::M3Transform" o-- "macbear_3d::src::scene::transform.dart::M3Transform"
"macbear_3d::src::scene::transform.dart::M3Transform" o-- "vector_math::vector_math.dart::Matrix4"

class "macbear_3d::src::scene::light.dart::M3ShadowCascade" {
  +Matrix4 projectionMatrix
  +double atlasBiasV
  +double atlasScaleV
  +String toString()
}

"macbear_3d::src::scene::light.dart::M3ShadowCascade" o-- "vector_math::vector_math.dart::Matrix4"

class "macbear_3d::src::scene::light.dart::M3Light" {
  {static} +Vector3 ambient
  +Vector3 color
  +bool isDirectional
  +bool isCameraAligned
  +double shadowNormalBias
  +double csmPaddingNear
  +double csmPaddingFar
  +List<M3ShadowCascade> cascades
  +Vector4 getDirection()
  {static} +Vector4 blendRGBA()
  {static} +Vector3 blendRGB()
  +void updateShadowCascades()
  -void _updateCascadeAtlasV()
  +void drawHelper()
}

"macbear_3d::src::scene::light.dart::M3Light" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::scene::camera.dart::M3Camera" <|-- "macbear_3d::src::scene::light.dart::M3Light"

abstract class "macbear_3d::src::scene::scene.dart::M3Scene" {
  +M3InputController? inputController
  -M3Light _light
  -M3Camera _camera
  +List<M3Camera> cameras
  +List<M3Entity> entities
  +M3Skybox? skybox
  -bool _isLoaded
  -double _totalTime
  +RenderingContext gl
  +M3Camera camera
  +M3Light light
  +bool isLoaded
  +double totalTime
  +void dispose()
  +dynamic load()
  +M3Entity addMesh()
  +void addEntity()
  +void addAxisGizmo()
  +void savePhysicsStates()
  +void update()
  -void _bindReflection()
  -void _applyReflectionCubemap()
  +void render()
  +void renderDebug()
  +void renderReflection()
  +void renderHelper()
  +void render2D()
  +Widget? buildUI()
}

"macbear_3d::src::scene::scene.dart::M3Scene" o-- "macbear_3d::src::input::touch.dart::M3InputController"
"macbear_3d::src::scene::scene.dart::M3Scene" o-- "macbear_3d::src::scene::light.dart::M3Light"
"macbear_3d::src::scene::scene.dart::M3Scene" o-- "macbear_3d::src::scene::camera.dart::M3Camera"
"macbear_3d::src::scene::scene.dart::M3Scene" o-- "macbear_3d::src::scene::skybox.dart::M3Skybox"
"macbear_3d::src::scene::scene.dart::M3Scene" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::scene::scene.dart::SampleScene" {
  -M3BoxGeom _geomCube
  -M3SphereGeom _geomSphere
  -M3CylinderGeom _geomCylinder
  -M3PlaneGeom _geomPlane
  +dynamic load()
  +void update()
  +void render2D()
}

"macbear_3d::src::scene::scene.dart::SampleScene" o-- "macbear_3d::src::geom::geom.dart::M3BoxGeom"
"macbear_3d::src::scene::scene.dart::SampleScene" o-- "macbear_3d::src::geom::geom.dart::M3SphereGeom"
"macbear_3d::src::scene::scene.dart::SampleScene" o-- "macbear_3d::src::geom::geom.dart::M3CylinderGeom"
"macbear_3d::src::scene::scene.dart::SampleScene" o-- "macbear_3d::src::geom::geom.dart::M3PlaneGeom"
"macbear_3d::src::scene::scene.dart::M3Scene" <|-- "macbear_3d::src::scene::scene.dart::SampleScene"

class "macbear_3d::src::scene::skybox.dart::M3Skybox" {
  +M3Material mtr
  -M3Texture _texCubemap
  {static} +RenderingContext gl
  {static} +dynamic createCubemap()
  +void dispose()
  +bool drawSkybox()
  {static} +bool drawDebug()
}

"macbear_3d::src::scene::skybox.dart::M3Skybox" o-- "macbear_3d::src::texture::material.dart::M3Material"
"macbear_3d::src::scene::skybox.dart::M3Skybox" o-- "macbear_3d::src::texture::texture.dart::M3Texture"
"macbear_3d::src::scene::skybox.dart::M3Skybox" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe" {
  +Vector3 position
  -M3Camera _camCapture
  +M3Entity? excludeEntity
  +int texSize
  +M3Texture? texCubemap
  -M3Framebuffer? _fbo
  +bool isMirror
  +void dispose()
  +void capture()
}

"macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe" o-- "macbear_3d::src::scene::camera.dart::M3Camera"
"macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe" o-- "macbear_3d::src::scene::entity.dart::M3Entity"
"macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe" o-- "macbear_3d::src::texture::texture.dart::M3Texture"
"macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe" o-- "macbear_3d::src::engine::framebuffer.dart::M3Framebuffer"

class "macbear_3d::src::scene::entity.dart::M3Entity" {
  -M3Transform _transform
  +RigidBody? rigidBody
  +M3Mesh? mesh
  +Vector4 color
  +M3ReflectionProbe? reflectionProbe
  +M3Axis physicsUpAxis
  +M3Bounding worldBounding
  -bool _boundsDirty
  {static} -Quaternion _qRotX90
  {static} -Quaternion _qRotXNeg90
  -Vector3 _prevPos
  -Quaternion _prevRot
  +Vector3 position
  +Quaternion rotation
  +Vector3 scale
  +Matrix4 matrix
  +M3Transform transform
  +void updateBounds()
  +void savePhysicsState()
  +void syncFromPhysics()
  +void syncToPhysics()
  +void update()
}

"macbear_3d::src::scene::entity.dart::M3Entity" o-- "macbear_3d::src::scene::transform.dart::M3Transform"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "oimo_physics::core::rigid_body.dart::RigidBody"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "macbear_3d::src::mesh::mesh.dart::M3Mesh"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "vector_math::vector_math.dart::Vector4"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "macbear_3d::src::scene::reflection_probe.dart::M3ReflectionProbe"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "macbear_3d::src::util::constants.dart::M3Axis"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "macbear_3d::src::geom::geom.dart::M3Bounding"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "vector_math::vector_math.dart::Quaternion"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::scene::entity.dart::M3Entity" o-- "vector_math::vector_math.dart::Matrix4"

class "macbear_3d::src::scene::camera.dart::M3Camera" {
  +Vector3 position
  +Quaternion rotation
  -Frustum _frustum
  +M3Euler euler
  +Matrix4 viewMatrix
  -Matrix4 _invViewMatrix
  +Vector3 target
  +Vector3 up
  +double distanceToTarget
  +List<double> csmSplitDistances
  -int _csmCount
  +double csmLambda
  +Matrix4 cameraToWorldMatrix
  +int csmCount
  +bool isVisible()
  +void updateFrustum()
  +void setViewport()
  -void _updateSplitDistances()
  +List<double> buildCSMSplits()
  +void setLookat()
  +void move()
  +void setEuler()
  -void _setRotationMatrix3()
  +void setRotationQuaternion()
  +String toString()
  +void drawHelper()
}

"macbear_3d::src::scene::camera.dart::M3Camera" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::scene::camera.dart::M3Camera" o-- "vector_math::vector_math.dart::Quaternion"
"macbear_3d::src::scene::camera.dart::M3Camera" o-- "vector_math::vector_math.dart::Frustum"
"macbear_3d::src::scene::camera.dart::M3Camera" o-- "macbear_3d::src::util::euler.dart::M3Euler"
"macbear_3d::src::scene::camera.dart::M3Camera" o-- "vector_math::vector_math.dart::Matrix4"
"macbear_3d::src::scene::camera.dart::M3Projection" <|-- "macbear_3d::src::scene::camera.dart::M3Camera"

class "macbear_3d::src::scene::camera.dart::M3Projection" {
  {static} +int halfW
  {static} +int halfH
  +Matrix4 projectionMatrix
  +int viewportX
  +int viewportY
  +int viewportW
  +int viewportH
  +double nearClip
  +double farClip
  +double degreeFovY
  +void setViewport()
  +void enableInfinite()
  +void refreshProjectionMatrix()
  +String toString()
  +double eyeDepthToFragZFromMatrix()
  +double eyeDepthToFragZFromNearFar()
}

"macbear_3d::src::scene::camera.dart::M3Projection" o-- "vector_math::vector_math.dart::Matrix4"

class "macbear_3d::src::engine::app_engine.dart::M3AppEngine" {
  {static} +M3AppEngine instance
  {static} +String version
  -FlutterAngle _angle
  -FlutterAngleTexture _sourceTexture
  {static} +Vector3 backgroundColor
  -bool _didInit
  +dynamic Function()? onDidInit
  +M3RenderEngine renderEngine
  +int initTick
  +M3TouchManager touchManager
  +M3KeyboardManager keyboard
  +M3ResourceManager resourceManager
  -Stopwatch _stopwatch
  +Ticker ticker
  -Duration _lastElapsed
  +double timeScale
  -bool _updating
  -int _fpsFrameCount
  -int _fpsLastTime
  -double _currentFps
  +int appWidth
  +int appHeight
  +double devicePixelRatio
  +int edgeInsetLeft
  +int edgeInsetTop
  +int edgeInsetRight
  +int edgeInsetBottom
  +M3Scene? activeScene
  +M3PhysicsEngine physicsEngine
  {static} +Framebuffer mainFbo
  +double fps
  +dynamic initApp()
  +void initKeyboard()
  +void dispose()
  +dynamic setScene()
  +void pause()
  +void resume()
  -double _getTime()
  +Widget getAppWidget()
  +dynamic onResize()
  +dynamic updateRender()
  -void _update()
  -dynamic _render()
  -Widget _flipY()
}

"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::engine::app_engine.dart::M3AppEngine"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "flutter_angle::desktop::angle.dart::FlutterAngle"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "flutter_angle::desktop::angle.dart::FlutterAngleTexture"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "vector_math::vector_math.dart::Vector3"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "null::dynamic Function()"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::engine::render_engine.dart::M3RenderEngine"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::input::touch.dart::M3TouchManager"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::input::keyboard.dart::M3KeyboardManager"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::engine::resource_manager.dart::M3ResourceManager"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "flutter::src::scheduler::ticker.dart::Ticker"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::scene::scene.dart::M3Scene"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "macbear_3d::src::physics::physics_engine.dart::M3PhysicsEngine"
"macbear_3d::src::engine::app_engine.dart::M3AppEngine" o-- "flutter_angle::shared::classes.dart::Framebuffer"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "macbear_3d::src::engine::app_engine.dart::M3AppEngine"

class "macbear_3d::src::engine::framebuffer.dart::M3Framebuffer" {
  +int frameW
  +int frameH
  -Framebuffer _fbo
  -WebGLTexture? _depthTexture
  -Renderbuffer? _depthRenderbuffer
  +RenderingContext gl
  +WebGLTexture depthTexture
  -void _checkStatus()
  +void bindFace()
  +void bind()
  +void dispose()
}

"macbear_3d::src::engine::framebuffer.dart::M3Framebuffer" o-- "flutter_angle::shared::classes.dart::Framebuffer"
"macbear_3d::src::engine::framebuffer.dart::M3Framebuffer" o-- "flutter_angle::shared::classes.dart::WebGLTexture"
"macbear_3d::src::engine::framebuffer.dart::M3Framebuffer" o-- "flutter_angle::shared::classes.dart::Renderbuffer"
"macbear_3d::src::engine::framebuffer.dart::M3Framebuffer" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"

class "macbear_3d::src::engine::shadow_map.dart::M3ShadowMap" {
  {static} -M3Program _prog
  -M3Framebuffer _framebuffer
  -M3Texture? _tex
  +RenderingContext gl
  +int mapW
  +int mapH
  +WebGLTexture depthTexture
  +M3Texture texDepth
  +String toString()
  +void dispose()
  +void renderDepthPass()
  +void drawDebugDepth()
}

"macbear_3d::src::engine::shadow_map.dart::M3ShadowMap" o-- "macbear_3d::src::program::program.dart::M3Program"
"macbear_3d::src::engine::shadow_map.dart::M3ShadowMap" o-- "macbear_3d::src::engine::framebuffer.dart::M3Framebuffer"
"macbear_3d::src::engine::shadow_map.dart::M3ShadowMap" o-- "macbear_3d::src::texture::texture.dart::M3Texture"
"macbear_3d::src::engine::shadow_map.dart::M3ShadowMap" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"
"macbear_3d::src::engine::shadow_map.dart::M3ShadowMap" o-- "flutter_angle::shared::classes.dart::WebGLTexture"

class "macbear_3d::src::engine::resources.dart::M3Resources" {
  {static} +M3Texture texWhite
  {static} +M3Texture texNormal
  {static} +M3Texture texDefaultCube
  {static} +M3DebugAxisGeom debugAxis
  {static} +M3DebugSphereGeom debugSphere
  {static} +M3BoxGeom debugFrustum
  {static} +M3SphereGeom debugDot
  {static} +M3PlaneGeom debugView
  {static} +M3BoxGeom unitCube
  {static} +M3OctahedralGeom unitBone
  {static} +M3OctahedralGeom unitOctahedral
  {static} +M3SphereGeom unitSphere
  {static} -M3Shape2D? _line
  {static} -M3Shape2D? _triangle
  {static} -M3Text2D? _text2D
  {static} -M3Rectangle2D? _rectUnit
  {static} +M3Program? programSimple
  {static} +M3Program? programSkybox
  {static} +M3Program? programRectangle
  {static} +M3ProgramEye? programSkyboxReflect
  {static} +M3Program? programExternalOES
  {static} +M3ProgramLighting? programSimpleLighting
  {static} +M3ProgramLighting? programTexture
  {static} +M3ProgramShadowmap? programShadowmap
  {static} +M3ProgramShadowCSM? programShadowCSM
  {static} -String _SkinNormal_vert
  {static} +M3Text2D text2D
  {static} +M3Shape2D line
  {static} +M3Shape2D triangle
  {static} +M3Rectangle2D rectUnit
  {static} +dynamic init()
  {static} +void setLightingProgram()
  {static} +void checkUpdate()
  {static} +void dispose()
}

"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::texture::texture.dart::M3Texture"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::geom::geom.dart::M3DebugAxisGeom"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::geom::geom.dart::M3DebugSphereGeom"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::geom::geom.dart::M3BoxGeom"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::geom::geom.dart::M3SphereGeom"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::geom::geom.dart::M3PlaneGeom"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::geom::geom.dart::M3OctahedralGeom"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::2d::shape_2d.dart::M3Shape2D"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::2d::text_2d.dart::M3Text2D"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::2d::shape_2d.dart::M3Rectangle2D"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::program::program.dart::M3Program"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::program::program.dart::M3ProgramEye"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::program::program.dart::M3ProgramLighting"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::program::program.dart::M3ProgramShadowmap"
"macbear_3d::src::engine::resources.dart::M3Resources" o-- "macbear_3d::src::program::program.dart::M3ProgramShadowCSM"

class "macbear_3d::src::engine::resource_manager.dart::M3ResourceManager" {
  +Map<String, M3Geom> geoms
  +Map<String, M3Mesh> meshes
  +Map<String, M3Program> programs
  +Map<String, M3Texture> textures
  +Map<String, M3TrueTypeParser> fonts
  +dynamic loadMesh()
  +dynamic loadFont()
  {static} +dynamic loadBuffer()
}

class "macbear_3d::src::engine::render_engine.dart::M3RenderEngine" {
  +RenderingContext gl
  -M3ShadowMap? _shadowMap
  -M3Projection _projection2D
  +M3RenderOptions options
  +M3RenderStats stats
  +M3ShadowMap? shadowMap
  +void dispose()
  +void createShadowMap()
  +void bindDefaultFramebuffer()
  +void setViewport()
  +void renderScene()
  +void render2D()
}

"macbear_3d::src::engine::render_engine.dart::M3RenderEngine" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"
"macbear_3d::src::engine::render_engine.dart::M3RenderEngine" o-- "macbear_3d::src::engine::shadow_map.dart::M3ShadowMap"
"macbear_3d::src::engine::render_engine.dart::M3RenderEngine" o-- "macbear_3d::src::scene::camera.dart::M3Projection"
"macbear_3d::src::engine::render_engine.dart::M3RenderEngine" o-- "macbear_3d::src::engine::render_engine.dart::M3RenderOptions"
"macbear_3d::src::engine::render_engine.dart::M3RenderEngine" o-- "macbear_3d::src::engine::render_engine.dart::M3RenderStats"

class "macbear_3d::src::engine::render_engine.dart::M3RenderOptions" {
  +M3DebugOptions debug
  +M3ShaderOptions shader
  +bool shadows
}

"macbear_3d::src::engine::render_engine.dart::M3RenderOptions" o-- "macbear_3d::src::engine::render_engine.dart::M3DebugOptions"
"macbear_3d::src::engine::render_engine.dart::M3RenderOptions" o-- "macbear_3d::src::engine::render_engine.dart::M3ShaderOptions"

class "macbear_3d::src::engine::render_engine.dart::M3DebugOptions" {
  +bool wireframe
  +bool showHelpers
  +bool showStats
  +bool showPhysicsStats
}

class "macbear_3d::src::engine::render_engine.dart::M3ShaderOptions" {
  -bool _perPixel
  -bool _cartoon
  -bool _pbr
  -bool _ibl
  -bool _pcf
  +bool isDirty
  +bool perPixel
  +bool cartoon
  +bool pbr
  +bool ibl
  +bool pcf
}

class "macbear_3d::src::engine::render_engine.dart::M3RenderStats" {
  +bool enabled
  +int frames
  +int vertices
  +int triangles
  +int entities
  +int culling
  +int reflection
  +void reset()
  +String toString()
}

class "macbear_3d::src::2d::sprite_2d.dart::M3Sprite2D" {
  -M3Rectangle2D _rect
  +M3Material mtr
  +double spriteW
  +double spriteH
  +double cellW
  +double cellH
  +int rowCount
  +int colCount
  +void dispose()
  +void draw()
}

"macbear_3d::src::2d::sprite_2d.dart::M3Sprite2D" o-- "macbear_3d::src::2d::shape_2d.dart::M3Rectangle2D"
"macbear_3d::src::2d::sprite_2d.dart::M3Sprite2D" o-- "macbear_3d::src::texture::material.dart::M3Material"

class "macbear_3d::src::2d::text_2d.dart::M3Text2D" {
  {static} +int firstChar
  {static} +int lastChar
  {static} -String _ascii
  {static} +dynamic createText2D()
  +void drawText()
}

"macbear_3d::src::2d::sprite_2d.dart::M3Sprite2D" <|-- "macbear_3d::src::2d::text_2d.dart::M3Text2D"

class "macbear_3d::src::2d::shape_2d.dart::M3Shape2D" {
  -int _primitiveType
  -int _vertexCount
  -int _usage
  -Vector2List _vertices
  -Vector2List _uvs
  -Buffer? _vertexBuffer
  -Buffer? _uvBuffer
  {static} +M3Material mtrWhite
  +RenderingContext gl
  {static} +M3Program prog2D
  +String toString()
  +void createVBO()
  +void dispose()
  +void draw()
  {static} +void drawLine()
  {static} +void drawTriangle()
  {static} +void drawImage()
  {static} +void drawTouches()
}

"macbear_3d::src::2d::shape_2d.dart::M3Shape2D" o-- "vector_math::vector_math_lists.dart::Vector2List"
"macbear_3d::src::2d::shape_2d.dart::M3Shape2D" o-- "flutter_angle::shared::classes.dart::Buffer"
"macbear_3d::src::2d::shape_2d.dart::M3Shape2D" o-- "macbear_3d::src::texture::material.dart::M3Material"
"macbear_3d::src::2d::shape_2d.dart::M3Shape2D" o-- "flutter_angle::desktop::wrapper.dart::RenderingContext"
"macbear_3d::src::2d::shape_2d.dart::M3Shape2D" o-- "macbear_3d::src::program::program.dart::M3Program"

class "macbear_3d::src::2d::shape_2d.dart::M3Rectangle2D" {
  -double _rectW
  -double _rectH
  +String toString()
  +void setRectangle()
  +void mappingUV()
}

"macbear_3d::src::2d::shape_2d.dart::M3Shape2D" <|-- "macbear_3d::src::2d::shape_2d.dart::M3Rectangle2D"

class "macbear_3d::src::video_bridge::video_bridge.dart::M3VideoBridge" {
  {static} -MethodChannel _channel
  {static} +dynamic registerSurface()
  {static} +dynamic updateSurface()
  {static} +dynamic release()
  {static} +dynamic play()
  {static} +dynamic pause()
  {static} +dynamic seekTo()
  {static} +dynamic getDuration()
  {static} +dynamic getPosition()
}

"macbear_3d::src::video_bridge::video_bridge.dart::M3VideoBridge" o-- "flutter::src::services::platform_channel.dart::MethodChannel"

class "macbear_3d::src::video_bridge::m3_video_bridge_method_channel.dart::MethodChannelM3VideoBridge" {
  +MethodChannel methodChannel
  +dynamic getPlatformVersion()
}

"macbear_3d::src::video_bridge::m3_video_bridge_method_channel.dart::MethodChannelM3VideoBridge" o-- "flutter::src::services::platform_channel.dart::MethodChannel"
"macbear_3d::src::video_bridge::m3_video_bridge_platform_interface.dart::M3VideoBridgePlatform" <|-- "macbear_3d::src::video_bridge::m3_video_bridge_method_channel.dart::MethodChannelM3VideoBridge"

abstract class "macbear_3d::src::video_bridge::m3_video_bridge_platform_interface.dart::M3VideoBridgePlatform" {
  {static} -Object _token
  {static} -M3VideoBridgePlatform _instance
  {static} +M3VideoBridgePlatform instance
  +dynamic getPlatformVersion()
}

"macbear_3d::src::video_bridge::m3_video_bridge_platform_interface.dart::M3VideoBridgePlatform" o-- "macbear_3d::src::video_bridge::m3_video_bridge_platform_interface.dart::M3VideoBridgePlatform"
"plugin_platform_interface::plugin_platform_interface.dart::PlatformInterface" <|-- "macbear_3d::src::video_bridge::m3_video_bridge_platform_interface.dart::M3VideoBridgePlatform"

class "macbear_3d::src::widgets::view.dart::M3View" {
  +State<M3View> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "macbear_3d::src::widgets::view.dart::M3View"

class "macbear_3d::src::widgets::view.dart::_M3ViewState" {
  -Timer? _debounceTimer
  +void initState()
  +dynamic initAppEngine()
  -dynamic _getValidSize()
  +void dispose()
  +void didChangeMetrics()
  +Widget build()
}

"macbear_3d::src::widgets::view.dart::_M3ViewState" o-- "dart::async::Timer"
"flutter::src::widgets::framework.dart::State" <|-- "macbear_3d::src::widgets::view.dart::_M3ViewState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin" <|-- "macbear_3d::src::widgets::view.dart::_M3ViewState"
"flutter::src::widgets::binding.dart::WidgetsBindingObserver" <|-- "macbear_3d::src::widgets::view.dart::_M3ViewState"


@enduml